# Generated by Django 4.0.4 on 2022-05-27 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('navat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name_plural': 'Food'},
        ),
    ]
