# Generated by Django 4.0.4 on 2022-05-27 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25, verbose_name='Name of staff')),
                ('description', models.TextField(verbose_name='Briefly about')),
                ('image', models.ImageField(upload_to='team/%Y/%m')),
            ],
            options={
                'verbose_name_plural': 'Team',
            },
        ),
    ]
